# Generated by Django 5.1.5 on 2025-02-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='day_planned',
            field=models.DateField(null=True),
        ),
    ]
