services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public/assets:/app/public/assets
      - /app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
