services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
      - shared_tmp:/tmp
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend

  recipe-extractor:
    build:
      context: ./recipe-extractors
    container_name: recipe-extractor
    volumes:
      - ./recipe-extractors:/app
      - shared_tmp:/tmp
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

volumes:
  shared_tmp:
