# Generated by Django 5.1.5 on 2025-04-03 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aisle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("llm_generated", models.BooleanField(default=False)),
                ("updated_by_user", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "calories_per_100g",
                    models.FloatField(help_text="energy in kcal per 100g", null=True),
                ),
                (
                    "protein_per_100g",
                    models.FloatField(help_text="grams of protein per 100g", null=True),
                ),
                (
                    "carbs_per_100g",
                    models.FloatField(
                        help_text="grams of carbohydrates per 100g", null=True
                    ),
                ),
                (
                    "sugar_per_100g",
                    models.FloatField(help_text="grams of sugar per 100g", null=True),
                ),
                (
                    "fat_per_100g",
                    models.FloatField(
                        help_text="grams of total fat per 100g", null=True
                    ),
                ),
                (
                    "fiber_per_100g",
                    models.FloatField(help_text="grams of fiber per 100g", null=True),
                ),
                (
                    "sodium_per_100mg",
                    models.FloatField(help_text="mg of sodium per 100g"),
                ),
                ("needs_review", models.BooleanField(default=True)),
                (
                    "aisle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.aisle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "prep_time",
                    models.IntegerField(help_text="Preparation time in minutes"),
                ),
                ("cook_time", models.IntegerField(help_text="Cooking time in minutes")),
                ("total_time", models.IntegerField(help_text="Total time in minutes")),
                ("source_url", models.URLField(blank=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("steps", models.JSONField(default=list)),
                ("main_ingredient", models.TextField(max_length=100, null=True)),
                ("needs_review", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_number", models.IntegerField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.CharField(max_length=255, null=True)),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "display_name",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("needs_review", models.BooleanField(default=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
