# Generated by Django 5.1.5 on 2025-04-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.IntegerField(help_text="Cooking time in minutes", null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(
                help_text="Preparation time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_time",
            field=models.IntegerField(help_text="Total time in minutes", null=True),
        ),
    ]
