# Generated by Django 5.1.5 on 2025-04-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="calories_per_100g",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="carbs_per_100g",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="fat_per_100g",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="fiber_per_100g",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="protein_per_100g",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="sodium_per_100mg",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="sugar_per_100g",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nutrients",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
