# Generated by Django 5.1.5 on 2025-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
