# Generated by Django 5.1.5 on 2025-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.JSONField(default=list, null=True),
        ),
    ]
