# Generated by Django 5.1.4 on 2025-03-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="main_ingredient",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
