# Generated by Django 5.1.4 on 2025-02-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_mealplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="carbs",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="protein",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="sugar",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cuisine",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="calories_per_100g",
            field=models.FloatField(help_text="Energy in kcal per 100g", null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="carbs_per_100g",
            field=models.FloatField(help_text="Carbohydrates per 100g", null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fat_per_100g",
            field=models.FloatField(help_text="Total fat per 100g", null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fiber_per_100g",
            field=models.FloatField(help_text="Fiber per 100g", null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="protein_per_100g",
            field=models.FloatField(help_text="Protein per 100g", null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="sugar_per_100g",
            field=models.FloatField(help_text="Sugar per 100g", null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="recipe",
            name="steps",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="display_name",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("recipe", "ingredient")},
        ),
    ]
