# Generated by Django 5.1.5 on 2025-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_cook_time_alter_recipe_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="added_by_extractor",
            field=models.BooleanField(default=False),
        ),
    ]
