# Generated by Django 5.1.4 on 2025-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipetag_recipe_is_confirmed_alter_recipe_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(default='../images/salad.jpg', upload_to='../images'),
        ),
    ]
