# Generated by Django 5.1.4 on 2025-03-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
