# Generated by Django 5.1.4 on 2025-02-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_ingredient_calories_remove_ingredient_carbs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="display_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
