# Generated by Django 5.1.5 on 2025-04-05 23:00

import backend.apps.recipes.models.ingredients
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipeingredient_added_by_extractor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="aisle",
            field=models.ForeignKey(
                blank=True,
                default=backend.apps.recipes.models.ingredients.get_default_aisle,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.aisle",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
