# Generated by Django 5.1.4 on 2025-03-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_aisle_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aisle',
            old_name='user_id',
            new_name='user',
        ),
    ]
