# Generated by Django 5.1.4 on 2025-03-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_url'),
        ('recipes', '0004_rename_user_id_aisle_user'),
    ]

    operations = [
    ]
