# Generated by Django 5.1.5 on 2025-04-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingredient_aisle_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
