# Generated by Django 5.1.5 on 2025-04-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_ingredient_needs_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
