# Generated by Django 5.1.4 on 2025-03-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_step'),
        ('recipes', '0005_merge_20250328_0116'),
    ]

    operations = [
    ]
