# Generated by Django 5.1.5 on 2025-03-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_merge_0004_step_0005_merge_20250328_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list),
        ),
    ]
