# Generated by Django 5.1.4 on 2025-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_merge_0004_step_0005_merge_20250328_0116"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.JSONField(default=list),
        ),
    ]
