# Generated by Django 5.1.4 on 2025-04-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
