name: Deploy to GCP & Supabase

on:
  push:
    branches:
      - prod-deploy

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push Docker Image
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/backend:latest ./backend
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/backend:latest \
            --platform managed \
            --region us-west1 \
            --port 8000 \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.SUPABASE_DB_URL }}" \
            --set-env-vars "ALLOWED_HOSTS=https://backend-service-102081122635.us-west1.run.app" \
            --set-env-vars "CSRF_TRUSTED_ORIGINS=https://mealchemy.app" \
            --set-env-vars "CORS_ALLOWED_ORIGINS=https://mealchemy.app"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push Docker Image
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/frontend:latest ./frontend
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/frontend:latest \
            --platform managed \
            --region us-west1 \
            --port 3000 \
            --allow-unauthenticated \
            --memory 1G
  # deploy-recipe-extractor:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Authenticate with GCP
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  #     - name: Set up Google Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v2

  #     - name: Build & Push Docker Image
  #       run: |
  #         gcloud auth configure-docker us-west1-docker.pkg.dev
  #         docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/recipe-extractor:latest ./recipe-extractor
  #         docker push us-west1-docker.pkg.dev/YOUR_PROJECT_ID/mealchemy-docker/recipe-extractor:latest

  #     - name: Deploy to Cloud Run
  #       run: |
  #         gcloud run deploy extractor-service \
  #           --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mealchemy-docker/recipe-extractor:latest \
  #           --platform managed \
  #           --region us-west1 \
  #           --allow-unauthenticated
